// Get register mnemonic from 8-bit address
// SFR and GPR
pub fn get_register_mnem(register: u32) -> String {
    if register > <u8>::max_value() as u32 {
        panic!("Register shouldn't be over 8 bits, but is actually {}", register);
    }

    match register {
        0xCC => String::from("ADCIC"),
        0xD0 => String::from("ADCON"),
        0x50 => String::from("ADDAT"),
        0x0C => String::from("ADDRSEL1"),
        0x0D => String::from("ADDRSEL2"),
        0x0E => String::from("ADDRSEL3"),
        0x0F => String::from("ADDRSEL4"),
        0xCD => String::from("ADEIC"),
        0x86 => String::from("BUSCON0"),
        0x8A => String::from("BUSCON1"),
        0x8B => String::from("BUSCON2"),
        0x8C => String::from("BUSCON3"),
        0x8D => String::from("BUSCON4"),
        0x25 => String::from("CAPREL"),
        0x40 => String::from("CC0"),
        0xBC => String::from("CC0IC"),
        0x41 => String::from("CC1"),
        0xBD => String::from("CC1IC"),
        0x42 => String::from("CC2"),
        0xBE => String::from("CC2IC"),
        0x43 => String::from("CC3"),
        0xBF => String::from("CC3IC"),
        0x44 => String::from("CC4"),
        0xC0 => String::from("CC4IC"),
        0x45 => String::from("CC5"),
        0xC1 => String::from("CC5IC"),
        0x46 => String::from("CC6"),
        0xC2 => String::from("CC6IC"),
        0x47 => String::from("CC7"),
        0xC3 => String::from("CC7IC"),
        0x48 => String::from("CC8"),
        0xC4 => String::from("CC8IC"),
        0x49 => String::from("CC9"),
        0xC5 => String::from("CC9IC"),
        0x4A => String::from("CC10"),
        0xC6 => String::from("CC10IC"),
        0x4B => String::from("CC11"),
        0xC7 => String::from("CC11IC"),
        0x4C => String::from("CC12"),
        0xC8 => String::from("CC12IC"),
        0x4D => String::from("CC13"),
        0xC9 => String::from("CC13IC"),
        0x4E => String::from("CC14"),
        0xCA => String::from("CC14IC"),
        0x4F => String::from("CC15"),
        0xCB => String::from("CC15IC"),
        0x30 => String::from("CC16"),
        0x31 => String::from("CC17"),
        0x32 => String::from("CC18"),
        0x33 => String::from("CC19"),
        0x34 => String::from("CC20"),
        0x35 => String::from("CC21"),
        0x36 => String::from("CC22"),
        0x37 => String::from("CC23"),
        0x38 => String::from("CC24"),
        0x39 => String::from("CC25"),
        0x3A => String::from("CC26"),
        0x3B => String::from("CC27"),
        0x3C => String::from("CC28"),
        0x3D => String::from("CC29"),
        0x3E => String::from("CC30"),
        0x3F => String::from("CC31"),
        0xA9 => String::from("CCM0"),
        0xAA => String::from("CCM1"),
        0xAB => String::from("CCM2"),
        0xAC => String::from("CCM3"),
        0x91 => String::from("CCM4"),
        0x92 => String::from("CCM5"),
        0x93 => String::from("CCM6"),
        0x94 => String::from("CCM7"),
        0x08 => String::from("CP"),
        0xB5 => String::from("CRIC"),
        0x04 => String::from("CSP"),
        0xE1 => String::from("DP2"),
        0xE3 => String::from("DP3"),
        0xE5 => String::from("DP4"),
        0xE7 => String::from("DP6"),
        0xE9 => String::from("DP7"),
        0xEB => String::from("DP8"),
        0x00 => String::from("DPP0"),
        0x01 => String::from("DPP1"),
        0x02 => String::from("DPP2"),
        0x03 => String::from("DPP3"),
        0x87 => String::from("MDC"),
        0x06 => String::from("MDH"),
        0x07 => String::from("MDL"),
        0x8F => String::from("ONES"),
        0x80 => String::from("P0L"),
        0x81 => String::from("P0H"),
        0x82 => String::from("P1L"),
        0x83 => String::from("P1H"),
        0xE0 => String::from("P2"),
        0xE2 => String::from("P3"),
        0xE4 => String::from("P4"),
        0xD1 => String::from("P5"),
        0xE6 => String::from("P6"),
        0xE8 => String::from("P7"),
        0xEA => String::from("P8"),
        0x60 => String::from("PECC0"),
        0x61 => String::from("PECC1"),
        0x62 => String::from("PECC2"),
        0x63 => String::from("PECC3"),
        0x64 => String::from("PECC4"),
        0x65 => String::from("PECC5"),
        0x66 => String::from("PECC6"),
        0x67 => String::from("PECC7"),
        0x88 => String::from("PSW"),
        0x18 => String::from("PW0"),
        0x19 => String::from("PW1"),
        0x1A => String::from("PW2"),
        0x1B => String::from("PW3"),
        0x98 => String::from("PWMCON0"),
        0x99 => String::from("PWMCON1"),
        0x5A => String::from("S0BG"),
        0xD8 => String::from("S0CON"),
        0xB8 => String::from("S0EIC"),
        0x59 => String::from("S0RBUF"),
        0xB7 => String::from("S0RIC"),
        0x58 => String::from("S0TBUF"),
        0xB6 => String::from("S0TIC"),
        0x09 => String::from("SP"),
        0xD9 => String::from("SSCCON"),
        0xBB => String::from("SSCEIC"),
        0xBA => String::from("SSCRIC"),
        0xB9 => String::from("SSCTIC"),
        0x0A => String::from("STKOV"),
        0x0B => String::from("STKUN"),
        0x89 => String::from("SYSCON"),
        0x28 => String::from("T0"),
        0xA8 => String::from("T01CON"),
        0xCE => String::from("T0IC"),
        0x2A => String::from("T0REL"),
        0x29 => String::from("T1"),
        0xCF => String::from("T1IC"),
        0x2B => String::from("T1REL"),
        0x20 => String::from("T2"),
        0xA0 => String::from("T2CON"),
        0xB0 => String::from("T2IC"),
        0x21 => String::from("T3"),
        0xA1 => String::from("T3CON"),
        0xB1 => String::from("T3IC"),
        0x22 => String::from("T4"),
        0xA2 => String::from("T4CON"),
        0xB2 => String::from("T4IC"),
        0x23 => String::from("T5"),
        0xA3 => String::from("T5CON"),
        0xB3 => String::from("T5IC"),
        0x24 => String::from("T6"),
        0xA4 => String::from("T6CON"),
        0xB4 => String::from("T6IC"),
        0x90 => String::from("T78CON"),
        0xD6 => String::from("TFR"),
        0x57 => String::from("WDT"),
        0xD7 => String::from("WDTCON"),
        0x8E => String::from("ZEROS"),
        0xF0 => String::from("r0"),
        0xF1 => String::from("r1"),
        0xF2 => String::from("r2"),
        0xF3 => String::from("r3"),
        0xF4 => String::from("r4"),
        0xF5 => String::from("r5"),
        0xF6 => String::from("r6"),
        0xF7 => String::from("r7"),
        0xF8 => String::from("r8"),
        0xF9 => String::from("r9"),
        0xFA => String::from("r10"),
        0xFB => String::from("r11"),
        0xFC => String::from("r12"),
        0xFD => String::from("r13"),
        0xFE => String::from("r14"),
        0xFF => String::from("r15"),
        _ => format!("{:02X}h (reg)", register)
    }
}

// Get register mnemonic from 8-bit address
// ESFR only
pub fn get_esfr_register_mnem(register: u32) -> String {
    if register > <u8>::max_value() as u32 {
        panic!("Register shouldn't be over 8 bits, but is actually {}", register);
    }

    match register {
        0x50 => String::from("ADDAT2"),
        0xB0 => String::from("CC16IC"),
        0xB1 => String::from("CC17IC"),
        0xB2 => String::from("CC18IC"),
        0xB3 => String::from("CC19IC"),
        0xB4 => String::from("CC20IC"),
        0xB5 => String::from("CC21IC"),
        0xB6 => String::from("CC22IC"),
        0xB7 => String::from("CC23IC"),
        0xB8 => String::from("CC24IC"),
        0xB9 => String::from("CC25IC"),
        0xBA => String::from("CC26IC"),
        0xBB => String::from("CC27IC"),
        0xBC => String::from("CC28IC"),
        0xC2 => String::from("CC29IC"),
        0xC6 => String::from("CC30IC"),
        0xCA => String::from("CC31IC"),
        0x80 => String::from("DP0L"),
        0x81 => String::from("DP0H"),
        0x82 => String::from("DP1L"),
        0x83 => String::from("DP1H"),
        0xE0 => String::from("EXICON"),
        0xE1 => String::from("ODP2"),
        0xE3 => String::from("ODP3"),
        0xE7 => String::from("ODP6"),
        0xE9 => String::from("ODP7"),
        0xEB => String::from("ODP8"),
        0xE2 => String::from("PICON"),
        0x1C => String::from("PP0"),
        0x1D => String::from("PP1"),
        0x1E => String::from("PP2"),
        0x1F => String::from("PP3"),
        0x18 => String::from("PT0"),
        0x19 => String::from("PT1"),
        0x1A => String::from("PT2"),
        0x1B => String::from("PT3"),
        0xBF => String::from("PWMIC"),
        0x84 => String::from("RP0H"),
        0xCE => String::from("S0TBIC"),
        0x5A => String::from("SSCBR"),
        0x59 => String::from("SSCRB"),
        0x58 => String::from("SSCTB"),
        0x28 => String::from("T7"),
        0xBD => String::from("T7IC"),
        0x2A => String::from("T7REL"),
        0x29 => String::from("T8"),
        0xBE => String::from("T8IC"),
        0x2B => String::from("T8REL"),
        0xC3 => String::from("XP0IC"),
        0xC7 => String::from("XP1IC"),
        0xCB => String::from("XP2IC"),
        0xCF => String::from("XP3IC"),
        _ => format!("{:02X}h (ext-reg)", register)
   }
}

pub fn get_word_reg_mnem(register: u32) -> String {
    if register > 0x0F as u32 {
        panic!("GPR shouldn't be over 4 bits, but is actually {}", register);
    }

    let reg : u8 = register as u8;
    format!("r{}", reg)
}

pub fn get_byte_reg_mnem(register: u32) -> String {
    if register > 0x0F as u32 {
        panic!("GPR shouldn't be over 4 bits, but is actually {}", register);
    }

    let reg : u8 = register as u8;

    if (reg & 0b00000001) == 1 {
        format!("rh{}", reg >> 1)
    } else {
        format!("rl{}", reg >> 1)
    }
}

pub fn get_sfr_mnem_from_physical(address: u32) -> Option<&'static str> {
    match address {
        0xFF98 => Some("ADCIC"),
        0xFFA0 => Some("ADCON"),
        0xFEA0 => Some("ADDAT"),
        0xF0A0 => Some("ADDAT2"),
        0xFE18 => Some("ADDRSEL1"),
        0xFE1A => Some("ADDRSEL2"),
        0xFE1C => Some("ADDRSEL3"),
        0xFE1E => Some("ADDRSEL4"),
        0xFF9A => Some("ADEIC"),
        0xFF0C => Some("BUSCON0"),
        0xFF14 => Some("BUSCON1"),
        0xFF16 => Some("BUSCON2"),
        0xFF18 => Some("BUSCON3"),
        0xFF1A => Some("BUSCON4"),
        0xEF04 => Some("C1BTR"),
        0xEF00 => Some("C1CSR"),
        0xEF06 => Some("C1GMS"),
        0xEF02 => Some("C1IR"),
        0xEF0A => Some("C1LGML"),
        0xEF0E => Some("C1LMLM"),
        0xEF08 => Some("C1UGML"),
        0xEF0C => Some("C1UMLM"),
        0xFE4A => Some("CAPREL"),
        0xFE80 => Some("CC0"),
        0xFF78 => Some("CC0IC"),
        0xF100 => Some("DP0L"),
        0xF102 => Some("DP1L"),
        0xF106 => Some("DP1H"),
        0xFFC2 => Some("DP2"),
        0xFFC6 => Some("DP3"),
        0xFFCA => Some("DP4"),
        0xFFCE => Some("DP6"),
        0xFFD2 => Some("DP7"),
        0xFFD6 => Some("DP8"),
        0xFE00 => Some("DPP0"),
        0xFE02 => Some("DPP1"),
        0xFE04 => Some("DPP2"),
        0xFE06 => Some("DPP3"),
        0xF1C0 => Some("EXICON"),
        0xFF0E => Some("MDC"),
        0xFE0C => Some("MDH"),
        0xFE0E => Some("MDL"),
        0xF1C2 => Some("ODP2"),
        0xF1C6 => Some("ODP3"),
        0xF1CE => Some("ODP6"),
        0xF1D2 => Some("ODP7"),
        0xF1D6 => Some("ODP8"),
        0xFF1E => Some("ONES"),
        0xFF00 => Some("P0L"),
        0xFF02 => Some("P0H"),
        0xFF04 => Some("P1L"),
        0xFF06 => Some("P1H"),
        0xFFC0 => Some("P2"),
        0xFFC4 => Some("P3"),
        0xFFC8 => Some("P4"),
        0xFFA2 => Some("P5"),
        0xFFCC => Some("P6"),
        0xFFD0 => Some("P7"),
        0xFFD4 => Some("P8"),
        0xFEC0 => Some("PECC0"),
        0xFEC2 => Some("PECC1"),
        0xFEC4 => Some("PECC2"),
        0xFEC6 => Some("PECC3"),
        0xFEC8 => Some("PECC4"),
        0xFECA => Some("PECC5"),
        0xFECC => Some("PECC6"),
        0xFECE => Some("PECC7"),
        0xF1C4 => Some("PICON"),
        0xF038 => Some("PP0"),
        0xF03A => Some("PP1"),
        0xF03C => Some("PP2"),
        0xF03E => Some("PP3"),
        0xFF10 => Some("PSW"),
        0xF030 => Some("PT0"),
        0xF032 => Some("PT1"),
        0xF034 => Some("PT2"),
        0xF036 => Some("PT3"),
        0xFE30 => Some("PW0"),
        0xFE32 => Some("PW1"),
        0xFE34 => Some("PW2"),
        0xFE36 => Some("PW3"),
        0xFF30 => Some("PWMCON0"),
        0xFF32 => Some("PWMCON1"),
        0xF17E => Some("PWMIC"),
        0xF108 => Some("RP0H"),
        0xFEB4 => Some("S0BG"),
        0xFFB0 => Some("S0CON"),
        0xFF70 => Some("S0EIC"),
        0xFEB2 => Some("S0RBUF"),
        0xFF6E => Some("S0RIC"),
        0xF19C => Some("S0TBIC"),
        0xFEB0 => Some("S0TBUF"),
        0xFF6C => Some("S0TIC"),
        0xFE12 => Some("SP"),
        0xF0B4 => Some("SSCBR"),
        0xFFB2 => Some("SSCCON"),
        0xFF76 => Some("SSCEIC"),
        0xF0B2 => Some("SSCRB"),
        0xFF74 => Some("SSCRIC"),
        0xF0B0 => Some("SSCTB"),
        0xFF72 => Some("SSCTIC"),
        0xFE14 => Some("STKOV"),
        0xFE16 => Some("STKUN"),
        0xFF12 => Some("SYSCON"),
        0xFE50 => Some("T0"),
        0xFF50 => Some("T01CON"),
        0xFF9C => Some("T0IC"),
        0xFE54 => Some("T0REL"),
        0xFE52 => Some("T1"),
        0xFF9E => Some("T1IC"),
        0xFE56 => Some("T1REL"),
        0xFFAC => Some("TFR"),
        0xFEAE => Some("WDT"),
        0xFFAE => Some("WDTCON"),
        0xF186 => Some("XP0IC"),
        0xF18E => Some("XP1IC"),
        0xF196 => Some("XP2IC"),
        0xF19E => Some("XP3IC"),
        0xFF1C => Some("ZEROS"),
        _      => None
    }
}
